name: Deploy to EC2 with Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout del código fuente
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Log in a DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3. Construir y subir la imagen Docker a DockerHub
    - name: Build and push Docker image
      run: |
        docker build . --file Dockerfile \
          --tag ${{ secrets.DOCKER_USERNAME }}/rick-morty-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/rick-morty-app:latest

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    # 1. Conectar a EC2 y desplegar la aplicación
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          sudo yum update -y
          sudo yum install -y docker
          sudo service docker start
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/rick-morty-app:latest
          sudo docker ps -q --filter "name=rick-morty-app" | grep -q . && \
          sudo docker stop rick-morty-app && \
          sudo docker rm rick-morty-app || true
          sudo docker run -d --name rick-morty-app -p 80:80 ${{ secrets.DOCKER_USERNAME }}/rick-morty-app:latest